TWITTER_KEY: "69dWqLEct4Swe3VmfYUbfg"
TWITTER_SECRET: "QpHS3vgM5ykR13Hg2wRjciTV66O8zYcD9PUjwfV9Q8"
OAUTH_TOKEN: "104939913-8dbjZkeyC4y9iihZRwiANoyWgvpDwMvytgPY6a9V"
OAUTH_TOKEN_SECRET: "1OVUDaCdbrUVTegoBnPMr8iWU98BsesTScpCLbcp2RRmp"
